baseurl: /
markdown: rdiscount
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

home: http://hattoriheiji.github.io/snippets
demo: http://hattoriheiji.github.io/snippets
base: http://hattoriheiji.github.io/snippets
weibo: http://localhost
edit_path: https://github.com/hattoriheiji/snippets/edit/gh-pages
new_path: https://github.com/hattoriheiji/snippets/new/gh-pages/snippets
author: 小胡子哥
author_en: Barret Lee
email: barret.china@gmail.com
author_info: <a href="http://www.barretlee.com">小胡子哥</a>
